version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  php71:
    build:
      context: .
      dockerfile: ./docker/php71/Dockerfile
    volumes:
      - ./www:/var/www
      - ./docker/php71/custom.ini:/usr/local/etc/php/conf.d/40-custom.ini
  mysql:
    image: mysql:5.7.22
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
#      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
      MYSQL_DATABASE: symfony_db
      MYSQL_ROOT_PASSWORD: 12345

volumes:
  mysql-data: